"""quests

Revision ID: 278354f0be44
Revises: 
Create Date: 2024-04-05 20:37:03.401791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '278354f0be44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_quests_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nfts_bought', sa.Integer(), nullable=False),
    sa.Column('nfts_sold', sa.Integer(), nullable=False),
    sa.Column('bids_made', sa.Integer(), nullable=False),
    sa.Column('servers_bought', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_quests_stats')
    # ### end Alembic commands ###
