"""migration message

Revision ID: a2c43b868621
Revises: 278354f0be44
Create Date: 2024-04-06 13:18:21.536362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2c43b868621'
down_revision = '278354f0be44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_quest_rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quest_type', sa.String(length=50), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('reward_claimed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_quest_rewards')
    # ### end Alembic commands ###
