"""message de votre migration

Revision ID: a2ff7ef03667
Revises: 
Create Date: 2024-03-22 20:31:32.714602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2ff7ef03667'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nft_bid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nft_id', sa.Integer(), nullable=False),
    sa.Column('bid_date', sa.DateTime(), nullable=False),
    sa.Column('bid_price_crypto', sa.Float(), nullable=False),
    sa.Column('bid_crypto_symbol', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['nft_id'], ['nft.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('profile_img_path',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               nullable=True,
               existing_server_default=sa.text("'images/avatar/avatar-1.png'"))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('profile_img_path',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'images/avatar/avatar-1.png'"))

    op.drop_table('nft_bid')
    # ### end Alembic commands ###
